### ISSUE TITLE
flutter_quill format change

### ISSUE THREAD

**Issue by adamkoch** [ArjanAswal/quill_markdown#1]
I was just testing this with flutter_quill pre-release (1.0.0-dev.2) and it appears the output format has changed. I am using `_controller.document.toDelta().toJson()` from flutter_quill, not sure if there is another conversion that is expected.

The json output from flutter_quill looks like:
```
[insert⟨ Test⏎ ⟩]
```

Whereas quill_markdown is expecting:
```
[{"insert":"Test"}]
```

**Comment by ArjanAswal** [comment]
Please try this 
`quillToMarkdown(jsonEncode(_controller.document.toDelta()));`

**Comment by adamkoch** [comment]
> Please try this
> `quillToMarkdown(jsonEncode(_controller.document.toDelta()));`

Thank you, working fine now :)
